//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// q_1_1_taylor.cpp
//
// Code generation for function 'q_1_1_taylor'
//

// Include files
#include "q_1_1_taylor.h"
#include "limits"
#include <cmath>

// Function Declarations
static double rt_powd_snf(double u0, double u1);

// Function Definitions
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (std::isnan(u0) || std::isnan(u1)) {
    y = std::numeric_limits<double>::quiet_NaN();
  } else {
    double d;
    double d1;
    d = std::abs(u0);
    d1 = std::abs(u1);
    if (std::isinf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = std::numeric_limits<double>::infinity();
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = std::numeric_limits<double>::infinity();
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = std::sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > std::floor(u1))) {
      y = std::numeric_limits<double>::quiet_NaN();
    } else {
      y = std::pow(u0, u1);
    }
  }
  return y;
}

void q_1_1_taylor(const double in1[4], double l, double, double m, double E,
                  double Jxx, double qvec[2])
{
  double b_qvec_tmp;
  double qvec_tmp;
  double qvec_tmp_tmp;
  double t10;
  double t11;
  double t12;
  double t13;
  double t14;
  double t16;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  // Q_1_1_TAYLOR
  //     QVEC = Q_1_1_TAYLOR(IN1,L,R,M,E,Jxx)
  //     This function was generated by the Symbolic Math Toolbox version 9.2.
  //     23-Apr-2023 16:27:15
  t2 = in1[0] * in1[0];
  t3 = rt_powd_snf(l, 3.0);
  t4 = rt_powd_snf(l, 5.0);
  t5 = rt_powd_snf(l, 7.0);
  t6 = in1[1] * in1[1];
  t8 = rt_powd_snf(l, 11.0);
  t7 = rt_powd_snf(t3, 3.0);
  t9 = t2 + t6;
  t10 = t9 * t9;
  t11 = rt_powd_snf(t9, 3.0);
  t13 = std::sqrt(t9);
  t12 = t10 * t10;
  t14 = 1.0 / rt_powd_snf(t13, 3.0);
  t13 *= l;
  t16 = std::sin(t13);
  qvec_tmp_tmp = E * Jxx;
  qvec_tmp = qvec_tmp_tmp * in1[0];
  b_qvec_tmp = t13 - t16;
  qvec[0] = (m *
                 ((((in1[0] * t3 / 3.0 - in1[0] * t4 * t9 / 30.0) +
                    in1[0] * t5 * t10 / 840.0) -
                   in1[0] * t7 * t11 / 45360.0) +
                  in1[0] * t8 * t12 / 3.99168E+6) *
                 9.81 -
             qvec_tmp * t14 * (t2 * t13 + t6 * t16)) -
            qvec_tmp * t6 * t14 * b_qvec_tmp;
  qvec[1] = (m *
                 ((((t3 * in1[1] / 3.0 - t4 * t9 * in1[1] / 30.0) +
                    t5 * t10 * in1[1] / 840.0) -
                   t7 * t11 * in1[1] / 45360.0) +
                  t8 * t12 * in1[1] / 3.99168E+6) *
                 9.81 -
             qvec_tmp_tmp * t14 * in1[1] * (t2 * t16 + t6 * t13)) -
            qvec_tmp_tmp * t2 * t14 * in1[1] * b_qvec_tmp;
}

// End of code generation (q_1_1_taylor.cpp)
